tabWidth: 4
printWidth: 100
semi: true
singleQuote: true
trailingComma: "es5"
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: "always"
proseWrap: "preserve"
# https://github.com/prettier/prettier-vscode
